### ISSUE TITLE
Create `Return` Fn?

### ISSUE THREAD

**Issue by ThomasAribart** [gvergnaud/hotscript#121]
Let's say that I want to replace the `ReturnType` of a function with `string`. There's no builtin way of doing that for the moment. I have to do:

```ts
import { Fn } from 'hoscript'

type MyFn = F.MapReturnType<Fn & { return: string }>
```

It would be nice to just have a `Return` Fn to do that:

```ts
import { Return } from 'hoscript'

type MyFn = F.MapReturnType<Return<string>>
```

**Comment by gvergnaud** [comment]
You should be able to do that with the Constant function:

```ts
import * as H from 'hotscript'

type X = H.Pipe<() => number, [H.Functions.MapReturnType<H.Constant<"hello">>]> 
//   ^? () => "hello"
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wBJwGZQiOAcgAsIZUBjKYMGQgWACgmmYBPMAUzgA04BeTADoACjU4AeABQBKAQD44AOwCuIAEacoAGjgBtDEIBiKpRRjAIS1EICyyMACVOMFVCUAVDpMMBhK6gwyEowEgBExJwANlEQYfLyALqKTAD0qXCZAHoA-CyMQA)

**Comment by ThomasAribart** [comment]
Sorry didn't see it!
