### ISSUE TITLE
[Proposal] New encoding for Functions

### ISSUE THREAD

**Issue by gvergnaud** [gvergnaud/HOTScript#20]
## Motivation

Our current function encoding creates a dichotomy between arguments received through `Apply` (`this["args"]`) and arguments passed explicitly via type parameters. This means every function needs to manually merge these two types of inputs, which is cumbersome and error prone.

In addition, we have a weird distinction between our "pipeable functions" that can't be called directly but only through `Call`, `Apply` or `Eval`, and regular generic types that can be called directly, but aren't "pipeable".

## Proposed Solution

Here is what I think could be a good solution:

* `Fn` extensions always receive their argument through `Apply`,  and read them using a new `Fn.args<this>` function.
* Wrap our `Fn` extensions in type aliases that support partial inputs by using a new `Curry` function.
* (mostly unrelated to this problem) rename `output` into `return`, to stay close to the semantics of a value-level function.

Pros:
* We can partially apply a function or give it all of its arguments using the same api: `MyFn<A, B, C>`
* We no longer have to manually merge our different types of arguments
* `Fn.args<this>` is easier to type than `this["args"]`
* `Fn.arg0<this>` is easier to type than `this["args"][0]`

```ts
/**
 * Core
 */
export interface Fn {
  args: unknown
  return: unknown;
}

export type Apply<fn extends Fn, args extends unknown[]> = (fn & { args: args })["return"];

namespace Fn {
  export type args<F> =
    F extends { args: infer args extends unknown[] } ? RemoveUnknownArrayConstraint<args> : never;

  export type arg0<F> =
    F extends { args: [infer arg, ...any] } ? arg : never;

  export type arg1<F> =
    F extends { args: [any, infer arg, ...any] } ? arg : never

  export type arg2<F> =
    F extends { args: [any, any, infer arg, ...any] } ? arg : never

  export type arg3<F> =
    F extends { args: [any, any, any, infer arg, ...any] } ? arg : never
}


export type Pipe<acc, xs extends Fn[]> = xs extends [
  infer first extends Fn,
  ...infer rest extends Fn[]
]
  ? Pipe<Apply<first, [acc]>, rest>
  : acc;

export type placeholder = "@hotscript/placeholder";
export type unset = "@hotscript/unset";



export interface CurryImpl<fn extends Fn, partialArgs extends unknown[]>
  extends Fn {
  return: MergeArgs<Fn.args<this>, partialArgs> extends infer args extends unknown[]
    ? Apply<fn, args>
    : never
}

type Curry<fn extends Fn, partialArgs extends unknown[]> =
  unset extends partialArgs[number]
  ? CurryImpl<fn, partialArgs>
  : placeholder extends partialArgs[number]
  ? CurryImpl<fn, partialArgs>
  : Apply<fn, partialArgs>

/**
 * Custom function
 */

/**
 * Parameters are assigned with Fn.args, Fn.arg0, Fn.arg1, Fn.arg2, etc.
 */
interface ExcludeNumberFn extends Fn {
  return: Fn.arg0<this> extends infer T ? T extends number ? never : T : never
  //                                      👆
  //                     Since we assigned T, this becomes
  //                     A naked type variable, which means
  //                     This expression distributes.
  //
  //                     It wouldn't with the simpler: 
  //                     `Fn.arg0<this> extends number ? never : Fn.arg0<this>`.
}

/**
 * Wrap this in a call with curry:
 */
type ExcludeNumber<T = unset> = Curry<ExcludeNumberFn, [T]>

/**
 * We can use it directly:
 */
type exclude1 = ExcludeNumber<"Gabriel" | 1 | 2 | "hello">
//    ^? "Gabriel" | "hello"

/**
 * Or through Apply!
 */
type exclude2 = Apply<ExcludeNumber, ["Gabriel" | 1 | 2 | "hello"]>
//    ^? "Gabriel" | "hello"


/**
 * It becomes more interesting with several parameters:
 */
interface PrependFn extends Fn {
  // you don't have to merge piped args with partial args manually:
  return: Fn.args<this> extends [infer Sep extends string, infer Str extends string]
    ? `${Sep}${Str}`
    : never
}

// Because this is done by `Curry`
type Prepend<Sep = unset, Str = unset> = Curry<PrependFn, [Sep, Str]>

// You can partially apply and pipe:
type re3 = Pipe<"Hello", [
  //  ^? "start_start_start_Hello"
  Prepend<"start_">,
  Prepend<"start_">,
  Prepend<"start_">,
]>

// You can use it directly:
type res2 = Prepend<"start", "end">
//    ^? "startend"

// Here is what you get if you partially applied:
type res4 = Prepend<"start">
//    ^? CurryImpl<PrependFn, ["start", "@hotscript/unset"]>

// And here what you get when you "pipe":
type res5 = Apply<Prepend<"start">, ["end"]>
//    ^? "startend"


/**
 * With this new encoding, we can also get rid of some weirdness 
 * We have with function of arity 2 like `Extends` when partially applied.
 */

// This is what you would expect:
export interface ExtendsFn extends Fn {
  return: [Fn.arg0<this>] extends [Fn.arg1<this>] ? true : false
}

// and we handle the swapping of arguments here instead: 
type Extends<A = unset, B = unset> =
  Curry<ExtendsFn, B extends unset ? [unset, A] : [A, B]>
  //                                       👆
  //                              Swap if B is unset

type res6 = Extends<2, number>
//   ^? true

type res7 = Pipe<"hello", [Extends<string>]>
  //   ^? true
  // The arguments are swapped here
```

### Use a function type to assign parameters and get the output

I also tried this approach of using a function type on `Fn` to both assign arguments and compute the output:

```ts
export interface Fn {
  args: unknown
  fn(): unknown;
}

export type Apply<fn extends Fn, args extends unknown[]> =
    ReturnType<(fn & { args: args })["fn"]>;
//      👆
//   We need to get the return type

export interface ExtendsImpl extends Fn {
  fn<A extends Fn.arg0<this>, B extends Fn.arg1<this>>():
  // 👆 args are declared like this
    [A] extends [B] ? true : false
  // 👆 and this is the body of our function
}

// This stays the same
type Extends<A = unset, B = unset> =
  Curry<ExtendsImpl, B extends unset ? [unset, A] : [A, B]>

type res6 = Extends<2, number>
//   ^? true

type res7 = Pipe<"hello", [Extends<string>]>
  //   ^? true
  ```

pros:
* The definition of arguments and return types of our function looks familiar
cons:
* It means TS will run `ReturnType<...>` a lot, which could be bad for perf

[👉 playground](https://www.typescriptlang.org/play?#code/PQKhCgAIUhhB7ATgUyiY5kA8AOSAukAlgHb7KIBmAhgMbKQBiJkA3lJNYgOYDOAXJACuJANYl4AdxIdKJQQAoAlJAC8APmFiJ0gNzgAvuEy4CkfAE8cDAII4cAGwsAeOZGzkSAE15MSAGk4eXw9kb18RcSkSAG0AXU1VSAAlZHwhRBIAFStkZwU3ADI2IL5BLj5IAyUYgCI5WoT9cBJqAFtkXhw6BmY2Dmw8REJLa1LeZ0ZAhBJefERqUkJQ8K0o6Xi1NZ1YhLUOSCZ3LE8fEoqBYhJKCnHj098ZuYWlqsgAfhTkNvgAN2QAKraaI2RALCxPeaLMjOC6aQQkZD-RDNQ6DMyjBgVAAMk2m8FmUNeSUiO0SBz8ADoLpNNCszjFSDdEKV7mEzpCXmRApTedQSBY4h9WQikRRUcchiNcqUAIx4uAE57Qwgk4HScmHQ7ManBWls1YxfkWQJM24VA0cpVE7mQXnUgVCz4W0XI4xo0zDcwyioAJgVnJVW1J0U1Wp1NMYdJO7N8RoFgWNpuu5p4lse1q5+B5fMdwpdkERboGnulYwqAGYA5mg2r1iQw9qSLq+Pr6XGk5wE12TVdmaz24rCVmcw7Bfm066KIZjCYpd6xgAFIjWWG0WiBLAhGOrZjxRKQLfpyAxDhmlmUIiIObH5j+Dj28+QFA3wd7uLgD+HT7L1d2RwuJe17ZiedC0AkgQvvg6gcOU67NOiXqYpAjg9AAFvADheLcSS1AAAhh+C8LQiArvgwCofQGFYRQtT6IhZYMCIvBpFs+GEcRpE4ORzFpHRs5zmYSwUDQ9BwBkiAWAAkm0jiuCwb4BChXD4EQ1AOKClSDiGGwJCWDx+P0hxyLCwS3s2NL4GhRC8OogQdDwyBeJp24GQAshQ3DIC5pl8IE3TDGpGnBOo6jKII-5OPJ9meU5LkwUY4DIbAEmAQpO5nHeymBepLnHjpuxhrxywZb4AWqblwQxCQQhtAARhQX7CilYLSbJDjRdlFXBXwMGHIIlHINR2EsoO5VBS51W1Q1iBNZ8LWSTJclyP5KkTSFsGQJFaWrTlPW2cYoAQNA4lzPAbSQJQIi0KpBJoBg4BHWgkBLQ4kANbQ52dOYaG9Olni8EQBKUs9i5cO0aQUL4XBYrwgPcIiXiQJIRBWVSFyBBGPDYpjFk8LKuMtr6gRpLQIPQBgwlUD0kAAKJYLQDhCNhABy00UK95lGZd8iQM4WTmS2uJWTZoXKGomgC4ONX1bcnxFrcghZBwwDAFq6sa5rWva4AvBuAGI7Ktq9r2sAMqkGJkiw-DiOQFkgQi74H1fbwhvG9rNiFtQohOQuDC-Fwal1Q4yCBJI1m0GhkAdPyLuHKrbta1k1nbjgL6AwSkBeDZ8xEHVQjkLw5OQKrrsJxrUmEJI8BCFhJAAOSV6jkcAAZY9wwvJ9GBkyzNwoKyyghtx3ovNyDiVPSdADqCw4D9NlXJwkC0Opb0o2jtCpfw91JTK9OM8zyBs7LiD88GsxpAeC0uHvTOs+ziCvYEMRZHpj1gM9k8MMvLBCCxxCEFnFAN0nBbwpjvMYXghA4FlFsG+B8j4zWcLUAA4tQOqpFkAOFqJAAAPpAGBeDfS4MgLUX6DgHDwFqDBeOWoAB67xDrvxOgAeRZFZRA1duCR22gAQm3shSBOAiFJG2s4OBd9j5PxQWgjBWC9I0MgPQ2cE8YAV3esgT6HRfA-BQFccgUFSDcGRk3SALFkTqWyhDfRAht5U1EgwRcKBrDeE5opbm8cLDV0zgSBukA0LUH+OYeAUdYooRXD7C4xi0bjQsZEto-IhArwsKAnmzgKQm2QLPRSQtnAO0CM8Qxdl0nzEFhUeUeTTE5xINwPqkAwpKEEM3AAJKwDJOADAtJNvMAwzcZyPTVgAIQ0dQX+DAHbEF8F4AkDA6oWEgM3K+vTkKOMyeyZwbSz4sRAl0lkaotmX1Ss4FZzivCPxPG0wIOzX7xwAJpeO-l1IKThOD2GefyJGOBwlb2QigCsWxfx5FqAACUwRQ2oT9S5KMOMctZtQ5gqQAPpUPvNCpxsL4XDCRUU1FqzvBIIxfgLFKLIAwrxXC-AiLkUcFJV4fFFLMVUpxScullLsUkrRWSglRLqUctpeS1lxKaUsoZWyoV-KRWCt5cKwljL2W4r5Vyql1y1Z3KEEvfkwg-6o0zleDR+AQHgIYC+YRcrmXivwOCkh7IqH9PVko21ILdHzzDtQQgni1VeUIEQSgkB3WPKSS8xwRAnLfJlC+AALP8qV5qbUKMUQw21NhvB+IoAwF1bqvGeuRr9FgfraifOsLUUNYwXwAFYtiiLFQS5FJ5ajWvkUbQ49q37HRgJPEx4zESSHcCQT6Wdqmhy-hq9SvBglZtIkjeAPrR0dGRsgK8XhERw0gB-Bg-jAlr0jldXtt0WBTqCKjOZRCHBEG9vM+mDxm7ZrCP68hczqCvODV4cm6BDpqyTvPZ1-iM1qqrjXJGgw9VbwYnokSNML2xlcaVQy7BjIkGcB7bJOJcmd0CAM0p+MUOi3qSkw4MQbBCkHDEAZTpzCICEAwQQNAHAsT6fHd5c6-HvODqYhgvBJAPs+dUyA+6Ki1TCERFNTrCTIGoF4QQhq6alQQ5stIaHZPQX2IcK+YjSpnPQ9pc+hBPgxEGsNCggQCOQEEPhtDek46NrLlZhO+tS7WesybDjs9vWQHQ-PYqxgfmdAAGywOk8TQs99qGNvtV53gAB2f54SkFkLBU-CD4RnAFOqeoczxcQsMIs7bX6pR+NkGhro9jnGfa-RQAJASKjIAgocNYa828QPIVSD8f4QJ6ygnBIGJYzgjyDmNPuLYPXoOnkOE+LABMzwphZFgYmE3+xYArMS0b4bFuTcPKWz8HAdNjc3AF+bm5ltraaoIQbBlGSre232W403kxzYW5dqb4a5ongu9dw8d2sCPc2id2MJ5RsE3u4eALo2KxPZiC93bIOvuuR+2dub-3Ru+lB+Do7h5oeGj+0j2UKP4jNGQuI5Ai4HDoUwiNCYW5AjV3wDgfOx4+tCiSP1pI33DSzduEBOYxLHyraght78l0ryvmg3pkn04+f48J8Tmi15nBQQp-nan0FNri6J1REX0vZcnntJThXgR2f4DS4IbX+cEKll9i9XgLMxQnyyAeZ+hGhv91I-MCjxnLojuQLjmUHlHIuVSLQNJhwC1xTMr1gU8RiUxP2rTsPcRiVG5KgZOnWx4jgAPJHvKRGnyR8YALkCXP+yR9SHMUH2fc-29O47zbkBvdeV9xo5wQfnLBF2t1IvIEYha-l-nFvQUc-AQNyeUv-fjy6ZV0NNXT3G8Z6G1n8JXg+8c7tLyWf1gvBt6ezX7ywQ-cN7n23nv6l9+a95PH-yc+F-69qSZzvVPu9L8pMryXpOG9rUP50aCKPN91-91P5vt6j8d4n5d4gRD7F5X7H6Uin736-58BxCe5jC0yySWBSRkDwAS6q5S7dYHhSQW5W5YHHjO6oB879ybRg7l4w7FST5j76aIBfbwEMBuQPqIHcTSSoHoHj6YHk48bAHR4WCbAM57BM5o4Mis4Xi56c7L7c7v687CiME4DMHIFsHUFq4y7v5Pw34650xIGsH4BoHKGYF66pbgHx4m7zjIRf56gcAwHCHQwx4R6v5R6h58EfgHgWF8A75WFz4uTEpyEKE6F6FP4UAv57TxSp66BAA)

**Comment by ecyrbe** [comment]
@gvergnaud found at that using currying breaks composition. But improvement on PartialApplication is still valid.
So this part was merged.

Closing.
