### ISSUE TITLE
[Bug report]: `Unions.Range` end value

### ISSUE THREAD

**Issue by brandonmcconnell** [gvergnaud/hotscript#46]
Re #41

I could be mistaken, but I don't think `Unions.Range` includes the final element. In other words, `Unions.Range<1, 3>` would match `1` and `2`, but not `3`.

Including the final element by default would be more intuitive in my opinion, and would only require a small adjustment to the function (something like `| EndValue`).

**Comment by gvergnaud** [comment]
It's included, the ordering is just a bit funky:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/9265418/219874834-bf827942-e4fe-4d21-89ff-5693b788fd15.png">


https://tsplay.dev/WG28Xm

**Comment by brandonmcconnell** [comment]
Ah nice! I didn't test. I just didn't see it accounted for in the implementation. Thanks!
