### ISSUE TITLE
Piping String to Object fails due to Zip; "Type instantiation is excessively deep"

### ISSUE THREAD

**Issue by audunolsen** [gvergnaud/hotscript#77]
<img width="578" alt="Screenshot 2023-03-03 at 23 41 05" src="https://user-images.githubusercontent.com/16224137/222845371-022c8fee-f747-4385-ab65-6030b198f0c6.png">

Attemnpting to make a route-function similar to the example shown in the readme, but simpler. Above code causes ts-error. `Type instantiation is excessively deep and possibly infinite. ts(2589)`. Toggling  `Tuples.Zip` seems  to trigger the error. In above example zip is utilised to transform `["user", "friend"]` to `[["user"], ["friend"]]` and then mapping the latter to `[["user", string], ["friend", string]]` and then ultimately to the final object. Thoughts?

[TS-playground repro](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgBWGApgGjgeQEYBW6AxjAM7YDKMUwAdgOYVwAqArmADbplwC+cAGZQIIOACIAFhHLFaYGOIDcAKBUwAnhjgAlCGxjpkAQyjGQZADws46AB6G6AE15ka9BgD44AXhRp0SxU4VkxguABtcJDqWkYyADpKLmAYS3EAenFPMJCQ9i4eBIAxYE5DKEtYj0TqU3IAdVTJdIAubJzo1g5uRIBZYzAq93iElloQNo7cvILehIAtNBn8nqKBobmigEEwDGdLNzivTrzuwsSWCABVOmAIOhXcQhJyEpEQAFE6dx5wgF0VJ41PZILAhGw6KR7nQ4CIDIEbPZHC44EcPJ4ABTwwytUJwMCmcxkPF6BEmMwWayeACUiHCUHQMDYUFh+CIpAS6B+tB4mMJlLINISjKcbGI6ExXX5xhgkmwEQF5mwpgY-zpPm8hLlIvQXGMEsxAANWgASBBKkB8I0qqAMGlPHHocI0lR8NROzGZNhkdBQMgZVo+v0ZYTAbkuQNhiPibAIcLBqB48ScaDoECx8LR5zJtBkNgZsJ8GlAA).

**Comment by audunolsen** [comment]
<img width="589" alt="Screenshot 2023-03-04 at 00 09 47" src="https://user-images.githubusercontent.com/16224137/222852369-6488902a-b28c-4447-9b96-a50ddfc421ca.png">

I guess I can just do this instead of course, which works fine.

I'm new to this lib and this approach to typescript, so I may have misunderstood the purpose of zip. I thought you could wrap any value in a tuple with it? So I'm not sure if this is an actual issue or just me not understanding it properly.

**Comment by gvergnaud** [comment]
Weird, this look like some sort of bug. I'll take a look.

Here is an alternative implementation using `Objects.Create`, which will takes a data structure and evaluate any function inside of it with the current arguments:

```ts
type RouteParams<T extends string> = Pipe<
  T,
  [
    Strings.Split<"/">,
    Tuples.Filter<Strings.StartsWith<":">>,
    Tuples.Map<Objects.Create<[Strings.Trim<":">, string]>>,
    Tuples.ToUnion,
    Objects.FromEntries
  ]
>;

type x = RouteParams<"/users/:user/friends/:friend">
```

**Comment by gvergnaud** [comment]
I think I fixed the issue: [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgBWGApgGjgeQEYBW6AxjAM7YDKMUwAdgOYVwAqArmADbplwC+cAGZQIIOACIAFhHLFaYGOIDcAKBUwAnhjgAlCGxjpkAQyjGQZADws46AB6G6AE15ka9BgD44AXhRp0SxU4VkxguABtcJDqWkYyADpKLmAYS3EAenFPMJCQ9i4eBIAxYE5DKEtYj0TqU3IAdVTJdIAubJzo1g5uRIBZYzAq93iElloQNo7cvILehIAtNBn8nqKBobmigEEwDGdLNzivTrzuwsSWCABVOmAIOhXcQhJyEpEQAFE6dx5wgF0VJ41PZILAhGw6KR7nQ4CIDIEbPZHC44EcPJ4ABTwwytUJwMCmcxkPF6BEmMwWayeACUiHCUHQMDYUFh+CIpAS6B+tB4mMJlLINISjKcbGI6ExXX5xhgkmwEQF5mwpgY-zpPm8hLlIvQXGMEsxAANWgASBBKkB8I0qqAMGlPHHocI0lR8NROzGZNhkdBQMgZVo+v0ZYTAbkuQNhiPibAIcLBqB48ScaDoECx8LR5zJtBkNgZsJ8GlAA)
