### ISSUE TITLE
[Feature Request] Object.set

### ISSUE THREAD

**Issue by Maggi64** [gvergnaud/hotscript#81]
Hi, thank you for the library 👍 
How about we add `Object.Set` which is similar to `Object.Update`. But you can update and set new paths.

```ts
Call<Objects.Set<'a.b', 2>, { a: 1 }>;
// { a: { b: 2 }}
```

**Comment by gvergnaud** [comment]
Hey, thanks for the feedback, the fact that `Object.Update` doesn't create new property is a bug actually, just fixed it! I'll publish a new release with the fix soon.

**Comment by gvergnaud** [comment]
Publish as v1.0.11
