### ISSUE TITLE
[Bug] AllPaths incorrect on const objects

### ISSUE THREAD

**Issue by Maggi64** [gvergnaud/hotscript#82]
The paths for the object `{ a: 1, b: 2, c: [{ d: 3 }, { e: 4 }] } as const` are incorrect.
But it works correctly for `{ a: 1, b: 2, c: [{ d: 3 }, { e: 4 }] }`.

**Reproduction:**
https://stackblitz.com/edit/typescript-wrimqa?file=index.ts

Thanks for looking into this 👍

**Comment by gvergnaud** [comment]
Thanks for opening this issue, this is fixed on the main branch

**Comment by gvergnaud** [comment]
Publish as v1.0.11

**Comment by Maggi64** [comment]
Thank you very much for the quick fix 👍
