### ISSUE TITLE
Support for Enumerate and Range

### ISSUE THREAD

**Issue by AnatoleLucet** [gvergnaud/hotscript#9]
I think an `Enumerate` and `Range` generic could be a nice addition to the Number/Tuple namespace.
I've been using these generics to generate lists of unioned numbers (maybe this could be a tuple instead of a union :shrug:) for discriminated unions of objects (e.g. http responses discriminated by status code).

See:
https://www.typescriptlang.org/play?#code/PTAEAsBdIBwZwFwjpAhgYwNYHsBuBTAJwDMAbbAdwDp1sBbYVYAZgE4AWVgVgEYB2ZsAAcrVgAZ2PHqBkB6gDoB9ABSARhgCUi4LIBQkAJ4x8oAKIA7AK50iqSPgA8OmQBUAcqHwAPO2YAmcUEs6ACMiABonUGcAQXR0D298PwCg0MIAbQBdUABeUCyIgD5cqNj0dIAiUiSAc0hwCuyvH38o10iAflK49NSiTMiEUyCbO3s3MPyqaZi4ydnyqtr6xszCgG4dPUNjAEkzSAAlVDMah2cAMQSWlKs0+euk1r7CYryTT3RSC18HSPMrKNzoUIjIAdZCLZzhdCjoNlszKhrHAYBhjAAJaAwADKaEgFjgAGFsL8AgBvSJeGDYQiQUAGIygfbEGl0WwAS2wiNIJX2RxOZ3sPDEYkmACYRfCZFSaXSGcZsRY4vg4AE8nzjqcHBLRaBmJLNtLPNTafSdqBDvhfOzCPh0JBOWZeQdNYL9br2AbKcbZWbGYTSOykpATIRCDTnfytfZPbquF6jSa5ebsUQCIRQ+HCJHXQ547qAGxegC+QA

PS amazing work on this lib. I love the overall design and the DX truly looks fantastic!

**Comment by gvergnaud** [comment]
Great suggestion

**Comment by brandonmcconnell** [comment]
@gvergnaud @AnatoleLucet I just realized that one of the issues I opened duplicates this one: #37

I'll close that one and continue the discussion here:

---

### Definition

```ts
type Enumerate<N extends number, Acc extends number[] = []> = Acc['length'] extends N
  ? Acc[number]
  : Enumerate<N, [...Acc, Acc['length']]>;

type IntRange<F extends number, T extends number> = Exclude<Enumerate<Simplify<T>>, Enumerate<F>> | T;
```

### Usage

```ts
type CustomRange = IntRange<20, 300>; // -> 20 | 21 | ... many more ... | 300
```

### Disclaimer & credit

This type is inspired (99% copied) from [this StackOverflow answer](https://stackoverflow.com/a/39495173/3824249) by [AlexG](https://stackoverflow.com/users/941384/alexg), with a slight modification to include the last number in the series (`| T`). Without this change, `IntRange<20, 300>` would match `20`–`299` instead or `20`–`300`.

**Comment by brandonmcconnell** [comment]
Per that last disclaimer, I do think it would be more intuitive to include the last/max number. So instead of this:

```ts
namespace HttpStatusCodes {
  export type Informational = IntRange<100, 200>;
  export type Success = IntRange<200, 300>;
  export type Redirection = IntRange<300, 400>;
  export type ClientError = IntRange<400, 500>;
  export type ServerError = IntRange<500, 600>;
}
```

we could do this:

```ts
namespace HttpStatusCodes {
  export type Informational = IntRange<100, 199>;
  export type Success = IntRange<200, 299>;
  export type Redirection = IntRange<300, 399>;
  export type ClientError = IntRange<400, 499>;
  export type ServerError = IntRange<500, 599>;
}
```

We could even make the option of whether to include the end or not a second boolean arg, which I personally think should default to true. With that enabled, if you wanted to keep the min and max values the same and not use the "X99" values, you could do this—

```ts
namespace HttpStatusCodes {
  export type Informational = IntRange<100, 200, false>;
  export type Success = IntRange<200, 300, false>;
  export type Redirection = IntRange<300, 400, false>;
  export type ClientError = IntRange<400, 500, false>;
  export type ServerError = IntRange<500, 600, false>;
}
```

This would work identically to the previous example. Here is the modified type to support that:

```ts
type IntRange<F extends number, T extends number, IncludeEnd = true> = IncludeEnd extends true ? (Exclude<Enumerate<T>, Enumerate<F>> | T) : (Exclude<Enumerate<T>, Enumerate<F>>);

type WithEnd    = IntRange<20, 300>;        // -> 20 | 21 | ... many more ... | 300
type WithoutEnd = IntRange<20, 300, false>; // -> 20 | 21 | ... many more ... | 299
```

**Comment by gvergnaud** [comment]
Well, here is a PR doing this: https://github.com/gvergnaud/hotscript/pull/41

**Comment by gvergnaud** [comment]
(closing because this has benn implemented)
